server:
  port: 8083

spring:
  # database local
  datasource:
    url: jdbc:mysql://j8a202.p.ssafy.io:3306/dokidb?serverTimezone=UTC&characterEncoding=UTF-8
    username: dokidoki
    password: dokidoki202
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  logging:
    level:
      org.hibernate.type: trace

cloud:
  aws:
    s3:
      bucket: dokidoki
    credentials:
      access-key: AKIAUEVS3DJH3EYUME6G
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

oauth2:
  google:
    client_id: 409728357789-pfbb5h8u9m4tib34v3qne7n7atat1tbc.apps.googleusercontent.com
    client_secret: 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
    token_uri: https://oauth2.googleapis.com/token
    profile_uri: https://www.googleapis.com/oauth2/v3/userinfo
    redirect_uri: https://j8a202.p.ssafy.io/api/users/oauth2/google/redirect
    #redirect_uri: http://localhost:8083/oauth2/google/redirect
  kakao:
    # REST API 키
    client_id: 355cfcf503170ecfb98fae9e4aa9a4df
    client_secret: DrtbGue1SrkzOWMJPLVx9g2by9YlNIWk
    redirect_uri: https://j8a202.p.ssafy.io/api/users/oauth2/kakao/redirect
    #redirect_uri: http://localhost:8083/oauth2/kakao/redirect
    token_uri: https://kauth.kakao.com/oauth/token

jwt:
  issuer: dokidoki.com
  secret: CEV5lPhLfU3RdjTqoHBfEHNrIWAGDRTZfFSLAO5X
  # unit is ms. 15 * 24 * 60 * 60 * 1000 = 15days 1296000000
  # 60 * 60 * 1000 = 3600000
  access_expiration: 3600000
  refresh_expiration: 1296000000

front:
  redirect_uri: https://j8a202.p.ssafy.io/redirect
  #redirect_uri: http://localhost:3000/redirect
